### ISSUE TITLE
RETURNING model after update

### ISSUE THREAD

**Issue by charles-cooper** [alevy/postgresql-orm#13]
Related to https://github.com/alevy/postgresql-orm/issues/2. If a model is updated, the current code (https://github.com/alevy/postgresql-orm/blob/master/Database/PostgreSQL/ORM/Model.hs#L1123) will simply return the input. However this is incorrect if there are native row-level triggers on the table that trigger on an update. I have a patch which looks something like

```diff
@@ -448,6 +448,7 @@ defaultModelUpdateQuery mi = Query $ BS.concat [
     , BS.intercalate ", " $ map (<> " = ?") $ modelQWriteColumns mi
     , " WHERE ", modelQPrimaryColumn mi, " = ?"
     , " AND ", modelQOwnerColumn mi, " = ?"
+    , " RETURNING ", BS.intercalate ", " (modelQColumns mi)
   ]
 
 -- | Default SQL insert query for a model.
@@ -635,13 +636,13 @@ insert c r = do
 
 -- | Update a model instance
 update
-  :: forall r. Model r
+  :: forall r. (Model r, FromRow r)
   => Connection -> UserId -> r -> IO (Either ValidationError r)
 update c owner r = do
-  n <- execute c (modelUpdateQuery qs) (UpdateRow owner r)
-  return $ case n of
-    1 -> Right r
-    _ -> Left . ValidationError $ "save: database updated " ++ show n ++ " records"
+  rows <- query c (modelUpdateQuery qs) (UpdateRow owner r)
+  return $ case rows of
+    [r] -> Right r
+    _ -> Left . ValidationError $ "save: database updated " ++ show (length rows) ++ " records"
   where
```

I can submit a pull request if that will help.

**Comment by alevy** [comment]
This seems right to me. A pull request would be best, thanks!

The only potential issue that comes to mind is that large models (say, those including large blob columns) would have to be fully transmitted back over the network after every update, which could be a bummer for latency in the common case (of no triggers). However, we don't support diff-updates anyway --- you have to transmit the whole model _to_ the DB on update.

I suppose that in the most common case (small models) this is really negligible, so maybe those kinds of optimizations are better left for dropping down into raw SQL `postgresql-simple`.
