### ISSUE TITLE
Add new "pg_migrate compile" behaviour

### ISSUE THREAD

**Issue by ian-ross** [alevy/postgresql-orm#25]
At the moment, running `pg_migrate` requires a valid GHC installation, because migration scripts are run directly using `runghc`.  Instead, it would be useful to provide a "compilation" mode to build a single "migrater" executable that can be used in the absence of a Haskell installation.  This mode would collect the migration scripts, editing them as necessary to make them into Haskell modules that could be compiled along with a suitable main program to make a standalone migration runner.

**Comment by alevy** [comment]
solved in #26
